version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "3800:3800"
    environment:
      - DATABASE_URL=file:./dev.db
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./server/prisma:/db
